name: CI

on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: {}  # Allows manual trigger from GitHub Actions UI
  schedule:
    - cron: "0 2 * * *"  # Runs daily at 2 AM UTC
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@main
    - name: Update Rust
      run: |
        rustup self update
        rustup update stable
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
