# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20

  - package-ecosystem: "cargo"
    directory: "/dexios-core"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/dexios-domain"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/dexios-gui"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/dexios"
    schedule:
      interval: "daily"
