name: Update Rust Version and Edition

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch: {}  # Allow manual triggering

jobs:
  update-cargo-toml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.3.0

      - name: Set up Rust
        uses: actions-rs/toolchain@v1.0.7  # Ensures updated version
        with:
          toolchain: stable
          override: true

      - name: Fetch latest Rust version and determine edition
        run: |
          # Fetch the latest Rust version and assumed latest edition
          latest_version=$(rustc --version | awk '{print $2}')
          latest_edition="2024"  # Assuming latest Rust edition for now
          echo "latest_version=$latest_version" >> $GITHUB_ENV
          echo "latest_edition=$latest_edition" >> $GITHUB_ENV
          echo "Fetched Rust Version: $latest_version and Edition: $latest_edition"

      - name: Find and update Cargo.toml files
        run: |
          changes_made=false
          echo "Latest Rust Version: $latest_version"
          echo "Latest Rust Edition: $latest_edition"
          
          # Find and process all Cargo.toml files
          for file in $(find . -name "Cargo.toml"); do
            echo "Checking $file"
            current_version=$(grep 'rust-version' "$file" | awk -F'"' '{print $2}')
            current_edition=$(grep 'edition' "$file" | awk -F'"' '{print $2}')
            
            # Update rust-version if newer is available
            if [ "$(printf '%s\n' "$latest_version" "$current_version" | sort -V | tail -n1)" != "$current_version" ]; then
              sed -i "s/rust-version = \".*\"/rust-version = \"$latest_version\"/g" "$file"
              changes_made=true
              echo "Updated rust-version in $file"
            fi
            
            # Update edition if it differs
            if [ "$latest_edition" != "$current_edition" ]; then
              sed -i "s/edition = \".*\"/edition = \"$latest_edition\"/g" "$file"
              changes_made=true
              echo "Updated edition in $file"
            fi
          done
          
          # Commit changes if any files were updated
          if [ "$changes_made" = true ]; then
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add .
            git commit -m "Update Cargo.toml files: rust-version and/or edition"
            git push origin HEAD
          else
            echo "No updates were needed."
          fi
